-- label prototype ref disabled requisite 默认有，不用统计
-- attrPosition 标签位置 tag（标签上） data (data域) method （method域）

DELETE FROM `TP_CIP_COMPS_DESC`;

INSERT INTO `pub_db`.`TP_CIP_COMPS_DESC`(`COMP_TAG`, `COMP_DESC`) VALUES 
('custom-input-interval', '[{attrPosition:"data",name:"v-model",defaultValue:"[]"},{attrPosition:"data",name:":startNum.sync"},{attrPosition:"data",name:":endNum.sync"},{attrPosition:"tag",name:"label",value:"起止日期"}]'),
('custom-input', '[{attrPosition:"data",name:"v-model"}]'),
('custom-date', '[{attrPosition:"data",name:"v-model"}]'),
('custom-date-childtype-range', '[{attrPosition:"data",name:"v-model",defaultValue:"[]"},{attrPosition:"tag",name:"type",value:"daterange"},{attrPosition:"data",name:":startDate.sync"},{attrPosition:"data",name:":endDate.sync"}]'),
('custom-selector', '[{attrPosition:"data",name:"v-model"},{name:"paraFile",attrPosition:"tag",value:""},{name:"listName",attrPosition:"tag",value:""}]'),
('custom-user-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-user-pwd', '[{attrPosition:"data",name:"v-model"}]'),
('custom-user-verify-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-cert-num', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:"custType",value:"0"},{attrPosition:"tag",name:"certType",value:"0"}]'),
('custom-cert-type', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:"custType",value:"1"}]'),
('custom-cust-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-cust-num', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:":auto-fill",value:true},{attrPosition:"tag",name:":fill-len",value:"16"},{attrPosition:"methods",name:":success",args:["custInfo"]},{attrPosition:"methods",name:":fail",args:["res"]}]'),
('custom-cust-addr', '[{attrPosition:"data",name:"v-model"},{attrPosition:"data",name:":province.sync",value:""},{attrPosition:"data",name:":city.sync",value:""},{attrPosition:"data",name:":county.sync",value:""},{attrPosition:"data",name:":street.sync",value:""},{attrPosition:"tag",name:":showAddressCascader",value:true},{attrPosition:"tag",name:":showAddress",value:true}]'),
('custom-phone-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-email', '[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["res"]},{attrPosition:"methods",name:":fail",args:["res"]}]'),
('custom-pinying-name', '[{attrPosition:"data",name:"v-model"}]'),
('custom-account', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:":read55ResFlg",value:true}]'),
('custom-sub-account', '[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["res"]},{attrPosition:"methods",name:":fail",args:["res"]}]'),
('custom-amount', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:":allowZero",value:true},{attrPosition:"tag",name:"currency",value:"156"}]'),
('custom-password', '[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["cardInfo"]}]'),
('custom-card-input-mode', '[{attrPosition:"data",name:"v-model"}]'),
('custom-currency', '[{attrPosition:"data",name:"v-model"}]'),
('custom-remittance-mark', '[{attrPosition:"data",name:"v-model"}]'),
('custom-withdrawal', '[{attrPosition:"data",name:"v-model"}]'),
('custom-cash-analysis-code', '[{attrPosition:"data",name:"v-model"}]'),
('custom-charge-mode', '[{attrPosition:"data",name:"v-model"}]'),
('custom-passbook-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-sealcard-num', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:":auto-fill",value:true},{attrPosition:"tag",name:"fill-len",value:"16"}]'),
('custom-coronal-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-deposit-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-voucher-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-payment-code', '[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["value"]},{attrPosition:"methods",name:":fail",args:[]}]'),
('custom-debit-credit-mark', '[{attrPosition:"data",name:"v-model"}]'),
('custom-account-classification', '[{attrPosition:"data",name:"v-model"}]'),
('custom-voucher-interval', '[{attrPosition:"data",name:"v-model"}]'),
('custom-certification-level', '[{attrPosition:"data",name:"v-model"}]'),
('custom-socialsec-prdcode', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:"codeType",value:"02"}]'),
('custom-escrow-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-equity-account', '[{attrPosition:"data",name:"v-model"}]'),
('custom-agent', '[{attrPosition:"data",name:"v-model"}]'),
('custom-ip-addr', '[{attrPosition:"data",name:"v-model"}]'),
('custom-plate-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-plate-type', '[{attrPosition:"data",name:"v-model"},{attrPosition:"tag",name:"inputModel",value:"0"}]'),
('custom-plate-color', '[{attrPosition:"data",name:"v-model"}]'),
('custom-etc-card-brand', '[{attrPosition:"data",name:"v-model"}]'),
('custom-vehicle-classification', '[{attrPosition:"data",name:"v-model"}]'),
('custom-vehicle-use', '[{attrPosition:"data",name:"v-model"}]'),
('custom-vehicle-color', '[{attrPosition:"data",name:"v-model"}]'),
('custom-vehicle-user-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-etc-blacklist-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-etc-blacklist-reason', '[{attrPosition:"data",name:"v-model"}]'),
('custom-debit-credit-account-type', '[{attrPosition:"data",name:"v-model"}]'),
('custom-etc-card-status', '[{attrPosition:"data",name:"v-model"}]'),
('custom-obu-status', '[{attrPosition:"data",name:"v-model"}]'),
('custom-machine-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-trade-flow-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-teller-flow-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-host-flow-num', '[{attrPosition:"data",name:"v-model"}]'),
('custom-user-num-project','[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["userInfo"]},{attrPosition:"methods",name:":fail",args:["res"]}]'),
('custom-user-pwd-project','[{attrPosition:"data",name:"v-model"}]'),
('custom-account-project','[{attrPosition:"data",name:"v-model"},{attrPosition:"methods",name:":success",args:["res","cardInfo"]},{attrPosition:"methods",name:":fail",args:["res"]}]'),
('custom-product-code', '[{attrPosition:"data",name:"v-model"}]'),
('custom-remark-code', '[{attrPosition:"data",name:"v-model"}]'),
('custom-bankno', '[{attrPosition:"data",name:"v-model"}]'),
('custom-water-elec-product-code', '[{attrPosition:"data",name:"v-model"}]'),
('custom-orgno', '[{attrPosition:"data",name:"v-model"}]'),
('custom-upload', '[{attrPosition:"data",name:"v-model"}]'),
('custom-download', '[{attrPosition:"data",name:"v-model"}]');



