export default {
  // 'custom-selector':'import CustomSelector from "@/common/utils/custom-selector.vue"',
  // 'custom-input':'import CustomInput from "@/common/utils/custom-input.vue"',
  "custom-user-num":'import customUserNum from "@/components/bank/teller/custom-user-num/CustomUserNum.vue"',
  "custom-user-pwd":'import customUserPwd from "@/components/bank/teller/custom-user-pwd/CustomUsePwd.vue"',
  "custom-user-verify-type":'import customUserVerifyType from "@/components/bank/teller/custom-user-verify-type/CustomUserVerifyType.vue"',
  "custom-cert-num":'import customCertNum from "@/components/bank/customer/custom-cert-num/CustomCertNum.vue"',
  "custom-cert-type":'import customCertType from "@/components/bank/customer/custom-cert-type/CustomCertType.vue"',
  "custom-customer-type":'import CustomCustomerType from "@/components/bank/customer/custom-customer-type/CustomCustomerType.vue"',
  "custom-cust-num":'import CustomCustNum from "@/components/bank/customer/custom-cust-num/CustomCustNum.vue"',
  "custom-cust-addr":'import CustomCustAddr from "@/components/bank/customer/custom-cust-addr/CustomCustAddr.vue"',
  "custom-phone-num":'import CustomPhoneNum from "@/components/bank/customer/custom-phone-num/CustomPhoneNum.vue"',
  "custom-email":'import CustomEmail from "@/components/bank/customer/custom-email/CustomEmail.vue"',
  "custom-pinying-name":'import CustomPinyingName from "@/components/bank/customer/custom-pinying-name/CustomPinyingName.vue"',
  "custom-account":'import CustomAccount from "@/components/bank/account/custom-account/CustomAccount.vue"',
  "custom-sub-account":'import CustomSubAccount from "@/components/bank/account/custom-sub-account/CustomSubAccount.vue"',
  "custom-password":'import CustomPassword from "@/components/bank/account/custom-password/CustomPassword.vue"',
  "custom-card-input-mode":'import CustomCardInputMode from "@/components/bank/account/custom-card-input-mode/CustomCardInputMode.vue"',
  "custom-currency":'import CustomCurrency from "@/components/bank/account/custom-currency/CustomCurrency.vue"',
  "custom-remittance-mark":	'import CustomRemittanceMark from "@/components/bank/account/custom-remittance-mark/CustomRemittanceMark.vue"',
  "custom-withdrawal":'import CustomWithdrawal from "@/components/bank/account/custom-withdrawal/CustomWithdrawal.vue"',
  "custom-cash-analysis-code":'import CustomCashAnalysisCode from "@/components/bank/account/custom-cash-analysis-code/CustomCashAnalysisCode.vue"',
  "custom-charge-mode":'import CustomChargeMode from "@/components/bank/account/custom-charge-mode/CustomChargeMode.vue"',
  "custom-passbook-num":'import CustomPassbookNum from "@/components/bank/account/custom-passbook-num/CustomPassbookNum.vue"',
  "custom-sealcard-num":'import CustomSealcardNum from "@/components/bank/account/custom-seal-card-num/CustomSealcardNum.vue"',
  "custom-coronal-num":'import CustomCoronalNum from "@/components/bank/account/custom-coronal-num/CustomCoronalNum.vue"',
  "custom-deposit-type":'import CustomDepositType from "@/components/bank/customer/custom-deposit-type/CustomDepositType.vue"',
  "custom-voucher-num":'import CustomVoucherNum from "@/components/bank/customer/custom-voucher-num/CustomVoucherNum.vue"',
  "custom-voucher-interval":'import CustomVoucherInterval from "@/components/bank/voucher/custom-voucher-interval/CustomVoucherInterval.vue"',
  "custom-certification-level":'import CustomCertificationLevel from "@/components/bank/agent/custom-certification-level/CustomCertificationLevel.vue"',
  "custom-socialsec-prdcode":'import CustomSocialsecPrdcode from "@/components/bank/agent/custom-socialsec-prdcode/CustomSocialsecPrdcode.vue"',
  "custom-escrow-num":'import CustomEscrowNum from "@/components/bank/loan/custom-escrow-num/CustomEscrowNum.vue"',
  "custom-equity-account":'import CustomEquityAccount from "@/components/bank/equity/custom-equity-account/CustomEquityAccount.vue"',
  "custom-agent":'import CustomAgent from "@/components/bank/other/custom-agent/CustomAgent.vue"',
  "custom-user-num-project":'import CustomUserNumProject from "@/components/project/teller/custom-user-num-project/CustomUserNumProject.vue"',
  "custom-user-pwd-project":'import CustomUserPwdProject from "@/components/project/teller/custom-user-pwd-project/CustomUserPwdProject.vue"',
  "custom-account-project":'import CustomAccountProject from "@/components/project/account/custom-account-project/CustomAccountProject.vue"',
  "custom-product-code":'import CustomProductCode from "@/components/project/account/custom-product-code/CustomProductCode.vue"',
  "custom-remark-code":'import CustomRemarkCode from "@/components/project/account/custom-remark-code/CustomRemarkCode.vue"',
  "custom-bankno":'import CustomBankno from "@/components/project/account/custom-bankno/CustomBankno.vue"',
  "custom-cust-num":'import CustomCustNum from "@/components/project/customer/custom-cust-num/CustomCustNum.vue"',
  "custom-water-elec-product-code":'import CustomWaterElecProductCode from "@/components/project/agent/custom-water-elec-product-code/CustomWaterElecProductCode.vue"',
  "custom-orgno":'import CustomOrgno from "@/components/project/branch/custom-orgno/CustomOrgno.vue"',
  "custom-upload":'import CustomUpload from "@/components/project/branch/custom-upload/CustomUpload.vue"',
  "custom-upload":'import CustomDownload from "@/components/project/branch/custom-download/CustomDownload.vue"'
}