export default {
  // 'custom-selector':'import CustomSelector from "@/common/utils/custom-selector.vue"',
  // 'custom-input':'import CustomInput from "@/common/utils/custom-input.vue"',
  
  "custom-user-num":'import CustomUserNum from "@/components/bank/teller/custom-user-num/CustomUserNum.vue"',
  "custom-user-pwd":'import CustomUsePwd from "@/components/bank/teller/custom-user-pwd/CustomUsePwd.vue"',
  "custom-user-verify-type":'import CustomUserVerifyType from "@/components/bank/teller/custom-user-verify-type/CustomUserVerifyType.vue"',
  "custom-cert-num":'import CustomCertNum from "@/components/bank/customer/custom-cert-num/CustomCertNum.vue"',
  "custom-cert-type":'import CustomCertType from "@/components/bank/customer/custom-cert-type/CustomCertType.vue"',
  "custom-cust-type":'import CustomCustType from "@/components/bank/customer/custom-cust-type/CustomCustType.vue"',
  "custom-cust-num":'import CustomCustNum from "@/components/project/customer/custom-cust-num/CustomCustNum.vue"',
  "custom-cust-addr":'import CustomCustAddr from "@/components/bank/customer/custom-cust-addr/CustomCustAddr.vue"',
  "custom-phone-num":'import CustomPhoneNum from "@/components/bank/customer/custom-phone-num/CustomPhoneNum.vue"',
  "custom-email":'import CustomEmail from "@/components/bank/customer/custom-email/CustomEmail.vue"',
  "custom-pinying-name":'import CustomPinyingName from "@/components/bank/customer/custom-pinying-name/CustomPinyingName.vue"',
  "custom-account":'import CustomAccount from "@/components/bank/account/custom-account/CustomAccount.vue"',
  "custom-sub-account":'import CustomSubAccount from "@/components/project/account/custom-sub-account/CustomSubAccount.vue"',
  "custom-amount":'import CustomAmount from "@/components/bank/account/custom-amount/CustomAmount.vue"',
  "custom-password":'import CustomPassword from "@/components/bank/account/custom-password/CustomPassword.vue"',
  "custom-card-input-mode":'import CustomCardInputMode from "@/components/bank/account/custom-card-input-mode/CustomCardInputMode.vue"',
  "custom-currency":'import CustomCurrency from "@/components/bank/account/custom-currency/CustomCurrency.vue"',
  "custom-remittance-mark":	'import CustomRemittanceMark from "@/components/bank/account/custom-remittance-mark/CustomRemittanceMark.vue"',
  "custom-withdrawal":'import CustomWithdrawal from "@/components/bank/account/custom-withdrawal/CustomWithdrawal.vue"',
  "custom-cash-analysis-code":'import CustomCashAnalysisCode from "@/components/bank/account/custom-cash-analysis-code/CustomCashAnalysisCode.vue"',
  "custom-charge-mode":'import CustomChargeMode from "@/components/bank/account/custom-charge-mode/CustomChargeMode.vue"',
  "custom-passbook-num":'import CustomPassbookNum from "@/components/bank/account/custom-passbook-num/CustomPassbookNum.vue"',
  "custom-sealcard-num":'import CustomSealcardNum from "@/components/bank/account/custom-sealcard-num/CustomSealcardNum.vue"',
  "custom-coronal-num":'import CustomCoronalNum from "@/components/bank/account/custom-coronal-num/CustomCoronalNum.vue"',
  "custom-deposit-type":'import CustomDepositType from "@/components/bank/customer/custom-deposit-type/CustomDepositType.vue"',
  "custom-voucher-num":'import CustomVoucherNum from "@/components/bank/account/custom-voucher-num/CustomVoucherNum.vue"',
  "custom-payment-code":'import CustomPaymentCode from "@/components/bank/account/custom-payment-code/CustomPaymentCode.vue"',
  "custom-debit-credit-mark":'import CustomDebitCreditMark from "@/components/bank/account/custom-debit-credit-mark/CustomDebitCreditMark.vue"',
  "custom-account-classification":'import CustomAccountClassification from "@/components/bank/account/custom-account-classification/CustomAccountClassification.vue"',
  "custom-voucher-interval":'import CustomVoucherInterval from "@/components/bank/voucher/custom-voucher-interval/CustomVoucherInterval.vue"',
  "custom-certification-level":'import CustomCertificationLevel from "@/components/bank/agent/custom-certification-level/CustomCertificationLevel.vue"',
  "custom-socialsec-prdcode":'import CustomSocialsecPrdcode from "@/components/bank/agent/custom-socialsec-prdcode/CustomSocialsecPrdcode.vue"',
  "custom-escrow-num":'import CustomEscrowNum from "@/components/bank/loan/custom-escrow-num/CustomEscrowNum.vue"',
  "custom-equity-account":'import CustomEquityAccount from "@/components/bank/equity/custom-equity-account/CustomEquityAccount.vue"',
  "custom-agent":'import CustomAgent from "@/components/bank/other/custom-agent/CustomAgent.vue"',
  "custom-ip-addr":'import CustomIpAddr from "@/components/bank/other/custom-ip-addr/CustomIpAddr.vue"',
  "custom-plate-num":'import CustomPlateNum from "@/components/bank/etc/custom-plate-num/CustomPlateNum.vue"',
  "custom-plate-type":'import CustomPlateType from "@/components/bank/etc/custom-plate-type/CustomPlateType.vue"',
  "custom-plate-color":'import CustomPlateColor from "@/components/bank/etc/custom-plate-color/CustomPlateColor.vue"',
  "custom-etc-card-brand":'import CustomEtcCardBrand from "@/components/bank/etc/custom-etc-card-brand/CustomEtcCardBrand.vue"',
  "custom-vehicle-classification":'import CustomVehicleClassification from "@/components/bank/etc/custom-vehicle-classification/CustomVehicleClassification.vue"',
  "custom-vehicle-use":'import CustomVehicleUse from "@/components/bank/etc/custom-vehicle-use/CustomVehicleUse.vue"',
  "custom-vehicle-color":'import CustomVehicleColor from "@/components/bank/etc/custom-vehicle-color/CustomVehicleColor.vue"',
  "custom-vehicle-user-type":'import CustomVehicleUserType from "@/components/bank/etc/custom-vehicle-user-type/CustomVehicleUserType.vue"',
  "custom-etc-blacklist-type":'import CustomEtcBlacklistType from "@/components/bank/etc/custom-etc-blacklist-type/CustomEtcBlacklistType.vue"',
  "custom-etc-blacklist-reason":'import CustomEtcBlacklistReason from "@/components/bank/etc/custom-etc-blacklist-reason/CustomEtcBlacklistReason.vue"',
  "custom-debit-credit-account-type":'import CustomDebitCreditAccountType from "@/components/bank/etc/custom-debit-credit-account-type/CustomDebitCreditAccountType.vue"',
  "custom-etc-card-status":'import CustomEtcCardStatus from "@/components/bank/etc/custom-etc-card-status/CustomEtcCardStatus.vue"',
  "custom-obu-status":'import CustomOBUStatus from "@/components/bank/etc/custom-obu-status/CustomOBUStatus.vue"',
  "custom-machine-num":'import CustomMachineNum from "@/components/bank/paymentmac/custom-machine-num/CustomMachineNum.vue"',
  "custom-trade-flow-num":'import CustomTradeFlowNum from "@/components/bank/flow/custom-trade-flow-num/CustomTradeFlowNum.vue"',
  "custom-teller-flow-num":'import CustomTellerFlowNum from "@/components/bank/flow/custom-teller-flow-num/CustomTellerFlowNum.vue"',
  "custom-host-flow-num":'import CustomHostFlowNum from "@/components/bank/flow/custom-host-flow-num/CustomHostFlowNum.vue"',
  "custom-user-num-project":'import CustomUserNumProject from "@/components/project/teller/custom-user-num-project/CustomUserNumProject.vue"',
  "custom-user-pwd-project":'import CustomUserPwdProject from "@/components/project/teller/custom-user-pwd-project/CustomUserPwdProject.vue"',
  "custom-account-project":'import CustomAccountProject from "@/components/project/account/custom-account-project/CustomAccountProject.vue"',
  "custom-product-code":'import CustomProductCode from "@/components/project/account/custom-product-code/CustomProductCode.vue"',
  "custom-remark-code":'import CustomRemarkCode from "@/components/project/account/custom-remark-code/CustomRemarkCode.vue"',
  "custom-bankno":'import CustomBankno from "@/components/project/account/custom-bankno/CustomBankno.vue"',
  "custom-water-elec-product-code":'import CustomWaterElecProductCode from "@/components/project/agent/custom-water-elec-product-code/CustomWaterElecProductCode.vue"',
  "custom-orgno":'import CustomOrgno from "@/components/project/branch/custom-orgno/CustomOrgno.vue"',
  "custom-upload":'import CustomUpload from "@/components/project/branch/custom-upload/CustomUpload.vue"',
  "custom-download":'import CustomDownload from "@/components/project/branch/custom-download/CustomDownload.vue"'
}